### ISSUE TITLE
DynamoDB -inMemory not working?

### ISSUE THREAD

**Issue by leppaott** [aaronshaf/dynamodb-admin#104]
Is there any way to make default amazon/dynamodb-local or cnadiminti/dynamodb-local to work with this? 

They have been started with -inMemory and GUI shows no tables. When I give -sharedDb GUI works.

**Comment by rchl** [comment]
It should work. I don't recall exactly now but without `-sharedDb` you might need to specify some random key and secret like: `AWS_REGION=eu-west-1 AWS_ACCESS_KEY_ID=local AWS_SECRET_ACCESS_KEY=local dynamodb-admin`
