### ISSUE TITLE
sh: bower: command not found

### ISSUE THREAD

**Issue by msaglietto** [aaronshaf/dynamodb-admin#13]
Hello ...  I was updating  dynamodb-admin and the post install fails because I dont have bower... 
So if its on the post-install does that make bower a dependency not a devDependency ?

```
> dynamodb-admin@1.13.0 postinstall /Users/msaglietto/.nvm/versions/node/v6.9.2/lib/node_modules/dynamodb-admin
> bower install

sh: bower: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! dynamodb-admin@1.13.0 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the dynamodb-admin@1.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by MatheusVellone** [comment]
https://docs.npmjs.com/cli/install#description
> By default, npm install will install all modules listed as dependencies in package.json.

I may be wrong, but I think moving it to dependency won't solve the error. I will try to reproduce and fix this tomorrow.

**Comment by MatheusVellone** [comment]
@msaglietto thanks for reporting it!
#15 will fix it
