### ISSUE TITLE
Queries should allow optional sort keys

### ISSUE THREAD

**Issue by achaphiv** [aaronshaf/dynamodb-admin#143]
I have a table with:

`h` = partition key
`r` = sort key

I should be able to search using just the partition key.
Instead it requires me to specify a sort key:

![query-sort-key-is-required](https://user-images.githubusercontent.com/678337/129779575-aa23f8ad-9a5d-48d8-82c6-48eccfdb86bb.png)

I can usually do `sort key >= 0` to effectively get the intended result, but it's a bit annoying to have to do.

## Version

I'm using the docker image.

`docker image inspect aaronshaf/dynamodb-admin`

```
[
    {
        "Id": "sha256:54883c9bcb9c6f87d8a761710aff78529f38406873d2b4447b0533caded30b46",
        "RepoTags": [
            "aaronshaf/dynamodb-admin:latest"
        ],
        "RepoDigests": [
            "aaronshaf/dynamodb-admin@sha256:8bd89cc717e3b418c97125c8bb968cf28b1cc87b385b1b57fd4f064c86ebc74f"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-07-27T08:42:48.704187572Z",
```

**Comment by zync-dreifschneider** [comment]
I really enjoy your tool, thank you very much!
However, this issue is really annoying as the Amazon Console allows it to explore the items just by only setting the PK either for the table indexes or the global/local secondary indexes. Would be great to see an update here soon!
