### ISSUE TITLE
Inaccessible host: `localhost'. This service may not be available in the `eu-west-1' region.

### ISSUE THREAD

**Issue by mr-py-007** [aaronshaf/dynamodb-admin#145]
Hi Aaron!

Thank you for your great work.

I want to use your solution to test dynamodb on local but I get this error when I run the command.
`AWS_REGION=eu-west-1 AWS_ACCESS_KEY_ID=local AWS_SECRET_ACCESS_KEY=local dynamodb-admin`

```
UnknownEndpoint: Inaccessible host: `localhost'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/usr/local/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/event_listeners.js:530:46)
    at Request.callListeners (/usr/local/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/request.js:688:14)
    at error (/usr/local/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/event_listeners.js:362:22)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (events.js:375:28)
    at ClientRequest.emit (domain.js:470:12)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:375:28)
```

I couldn't find the answer in the issues.
Could you please let me know how can I resolve this issue and make it work.
I am on Ubuntu 20.04.

Thanks in advance

**Comment by rchl** [comment]
Are you sure that you are running a local dynamodb instance?

**Comment by mr-py-007** [comment]
@rchl 
Yeah, I followed this. https://hub.docker.com/r/aaronshaf/dynamodb-admin/

**Comment by rchl** [comment]
https://hub.docker.com/r/aaronshaf/dynamodb-admin/ is just for the dynamodb-admin, you still need to have a separate docker container running `amazon/dynamodb-local`. Have you started that one too? Do you see it running with `docker ps` (or `sudo docker ps`) and what ports are exposed for it (check `PORTS` column)

**Comment by mr-py-007** [comment]
So I have both containers running here
```
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS          PORTS                                       NAMES
2e2befdafd53   aaronshaf/dynamodb-admin       "docker-entrypoint.s…"   10 seconds ago   Up 9 seconds    0.0.0.0:8001->8001/tcp, :::8001->8001/tcp   engine_dynamodb-admin_1
d3afa74ff4ff   amazon/dynamodb-local:latest   "java -jar DynamoDBL…"   10 seconds ago   Up 10 seconds   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   engine_dynamodb-local_1

```

But I cannot access the admin `http://localhost:8001`

**Comment by mr-py-007** [comment]
I also try to connect dynamodb in python using boto3
But it does not work either

**Comment by rchl** [comment]
For `aws dynamodb list-tables --endpoint-url http://localhost:8000` I would expect a credentials error but not read timeout. That sounds like there is some bigger issue with communicating with your docker containers. Maybe some sort of firewall or configuration issue. I don't know enough about docker to help but it's likely not related to this project specifically.

**Comment by abraham-lawson** [comment]
@mr-py-007  Let config `DYNAMO_ENDPOINT` environment variable in your docker-compose file.
```
version: '3.7'

services:
  dynamoDB-local:
    image: amazon/dynamodb-local:1.13.6
    ports:
      - '4569:8000'
  dynamo-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - '8002:8001'
```

**Comment by rchl** [comment]
Hope that the last answer helped. Closing.

**Comment by vutreras** [comment]
Hi, Something similar happens to me with node 18 but it works with node 12 and 14.

**Comment by filknight** [comment]
Also have experienced the same.
I have localstack with a running dynamodb, localstack configured with standard port 4566
dynamodb is accessible using aws cli with '--endpoint-url=http://localhost:4566' option

running:
PORT=8010 DYNAMO_ENDPOINT=http://localhost:4566 AWS_ACCESS_KEY_ID=local AWS_SECRET_ACCESS_KEY=local dynamodb-admin

with dynamodb-admin installed in node v14.17.2 and v16.16.0 the admin UI appears successfully (port 8010)

with dynamodb-admin installed in node v17.2.0 or v18.12.1, the admin fails to connect as shown by op.

**Comment by hs-shakhzod-khodjaev** [comment]
same here with the last two comments

**Comment by joe4dev** [comment]
If you are using macOS, this is likely related to breaking changes in Node v17 favoring IPv6 over IPv4 depending on the DNS configuration. Try using using `127.0.0.1` instead of `localhost` as hostname.

See full explanation here: https://github.com/localstack/aws-cdk-local/issues/76#issuecomment-1412590519

**Comment by chrisdugne** [comment]
> environment:
>       - DYNAMO_ENDPOINT=dynamodb-local:8000

from @lawson-ng [comment](https://github.com/aaronshaf/dynamodb-admin/issues/145#issuecomment-981049893) was the fix for me here. Thanks.

**Comment by Morvanmc** [comment]
I had this issue today and was the coredns of kubernetes. The pods was unhealthy and i solved updated the add-on.
