### ISSUE TITLE
Problem accessing non-local dynamo

### ISSUE THREAD

**Issue by Nath5** [aaronshaf/dynamodb-admin#16]
Is it possible to hook this up to dynamo hosted on AWS instead of locally.  I exported my access key and secret key and tried without setting the dynamo endpoint but I kept getting:

```
{
  "error": {
    "message": "connect ECONNREFUSED 127.0.0.1:8000",
    "code": "NetworkingError",
    "errno": "ECONNREFUSED",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 8000,
    "region": "us-east-1",
    "hostname": "localhost",
    "retryable": true,
    "time": "2017-08-16T14:35:53.351Z"
  }
}
```

so I tried setting the endpoint to https://dynamodb.us-east-1.amazonaws.com but that resulted in the following error.

```
{
  "error": {
    "message": "400",
    "code": "UnknownError",
    "statusCode": 400,
    "time": "2017-08-16T14:30:53.374Z",
    "retryable": false,
    "retryDelay": 0
  }
}
```

Any help on getting this working would be most appreciated.

Thanks,
Nathan

**Comment by MatheusVellone** [comment]
My guess is this is an auth error.
I had my AWs credentials configured to use the `aws-cli`, which configured some env vars automatically `AWS_REGION`, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
In my case, if I just don't provide a `DYNAMO_ENDPOINT` I can access the AWS Dynamo tables.
If you don't want to configure `aws-cli` you can set those environment variables when running the command to use them to authenticate with AWS.

You can check [here](https://github.com/aaronshaf/dynamodb-admin/blob/master/index.js#L27) the env vars used to mount the config object that will be used to create dynamo objects.

**Comment by MatheusVellone** [comment]
@Nath5 could you make it work ?

**Comment by aaronshaf** [comment]
I don't plan on officially supporting non-local dynamo, especially because we want to add destructive conveniences for local development.

**Comment by nathaniel-holder** [comment]
So, how about unofficially?  Any suggestions on getting dynamodb-admin to be able to query remote AWS endpoint?  Or other tools?  I haven't seen any decent query tool out there for dynamodb.
Thanks!

**Comment by MatheusVellone** [comment]
@nathaniel-holder, by default dynamodb-admin doesn't support non-local environments, but you can hack it to allow usage outside your local.

[This line](https://github.com/aaronshaf/dynamodb-admin/blob/master/index.js#L37) block the production usage. If you remove it, you can achiev what you want.

But be careful. As this tool isn't designed to be used in production, any wrong click, or bug, can destroy your data.
