### ISSUE TITLE
Docker tag "latest" is outdated

### ISSUE THREAD

**Issue by pencil** [aaronshaf/dynamodb-admin#182]
The `latest` tag on [Docker Hub](https://hub.docker.com/r/aaronshaf/dynamodb-admin/tags) was last pushed to in July. Any chance to get a more recent image pushed?

**Comment by rchl** [comment]
I'm not sure how is that set up. I could make a proper github action for building the container but would need access to the dockerhub repository (or have a new official account created for it). @aaronshaf

**Comment by aaronshaf** [comment]
@rchl You're listed as a collaborator on https://hub.docker.com/repository/docker/aaronshaf/dynamodb-admin

What can I do to help?

**Comment by rchl** [comment]
I don't see myself being listed anywhere as a contributor on docker hub. I guess I could just try publishing anyway but I didn't get to it so far.

**Comment by rchl** [comment]
@aaronshaf but since I have your attention... could you disable circleCi building on https://app.circleci.com/settings/project/github/aaronshaf/dynamodb-admin

Apparently I'm not an admin so can't do it.

**Comment by rchl** [comment]
I was able to update the tag actually. Just released latest version as `latest`.

**Comment by pencil** [comment]
Thanks, appreciate it!
