### ISSUE TITLE
`latest` image is arm-based?

### ISSUE THREAD

**Issue by masterful** [aaronshaf/dynamodb-admin#202]
Hi friend(s)!

I'm not sure if this is the best place to post this - but the `latest` docker image published on Docker Hub (https://hub.docker.com/r/aaronshaf/dynamodb-admin/tags) switched from an `AMD` base to an `ARM` base (and has a different user as the publisher). I'm not sure if this was intentional or not - but thought I'd mention it here since if someone was previously using the latest image as part of their workflow, it could break (it did on mine).

My current workaround is to be more explicit with the tag we're pulling:
```diff
- image: aaronshaf/dynamodb-admin
+ image: aaronshaf/dynamodb-admin:dependabot_npm_and_yarn_aws-sdk-2.952.0
```

I've found that if you're building on an M1 mac, you can update the Dockerfile / docker commands to specify the platform as `--platform=linux/amd64` so that it builds for an AMD platform.
```Dockerfile
FROM        --platform=linux/amd64 base-image-here
```

Thanks so much! 

Edit: For those encountering the same error, they'd see this in the container logs (and a CrashLoopBackoff if you're running in Kubernetes):
```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by rchl** [comment]
I think it should be good now (should include both architectures).

(I'm the current maintainer of the project so that's why the images were pushed by a different account)

**Comment by masterful** [comment]
Yep! Just tested using the `latest` tag again and it pulls the correct architecture, thanks!
