### ISSUE TITLE
Docs could mention that you can only see the tables from another app if the keys match

### ISSUE THREAD

**Issue by hughjdavey** [aaronshaf/dynamodb-admin#219]
I had an issue this morning where my Spring Boot app using the AWS local dynamo docker image could not see the tables I was making using dynamodb-admin. Eventually I realized the issue was that the Java app used access key `""` but dynamodb-admin used access key `key`. I didn't know from reading the docs that you basically see a different dynamo instance per key. I confirmed this by changing to a third key with dynamodb-admin and I no longer being able to see the tables I had made.

Happy to submit a PR with a line or two added to `README.md` explaining this if you don't mind. Thanks

**Comment by rchl** [comment]
PR welcome.

**Comment by rchl** [comment]
Fixed in #220
