### ISSUE TITLE
Viewing a table content only displays columns for the attributes of the first item

### ISSUE THREAD

**Issue by etiennellipse** [aaronshaf/dynamodb-admin#24]
See https://github.com/aaronshaf/dynamodb-admin/blob/master/views/scan.ejs#L149

* In a table, save an item with 3 attributes
* Then in that same table, save another item with 4 attributes (one more)
* Open that table with dynamodb-admin

You will only be able to see the attributes defined on the first item. To be comprehensive, the code in the scan view should parse all the items in the page and make sure to iterate over all the existing attributes.

**Comment by rchl** [comment]
I've created pull request for it. Thanks for identifying the problem exactly.

**Comment by Dunge** [comment]
Any chance to do a release and update the NPM package with this fix? I just tested the application and love it and would love to share it with my dev team, but this bug prevent me since all our data attributes are dynamic.

**Comment by aaronshaf** [comment]
@rchl You interested in becoming a collaborator?

**Comment by rchl** [comment]
Seems like a low-maintenance project so sure, I can find time for that. :)

**Comment by aaronshaf** [comment]
@rchl Are you on npm?

**Comment by rchl** [comment]
I am now - rchl.

**Comment by aaronshaf** [comment]
Not seeing it: https://www.npmjs.com/~rchl

**Comment by rchl** [comment]
It does show up for me on that URL. Even when not logged-in/in private mode.
Maybe you just need to wait a bit more - I've just created the account.

**Comment by aaronshaf** [comment]
✅
