### ISSUE TITLE
UI assumes epochs are in milliseconds

### ISSUE THREAD

**Issue by adammcdonagh** [aaronshaf/dynamodb-admin#244]
Hello,
I have noticed that it seems when an epoch is rendered in the table view, it seems to assume that the epoch is in milliseconds (a javascript thing) rather than seconds.

I'm storing an expiry time as a TTL value for dynamoDB, which is always a value in seconds. When I hover over the value, the popup will always show a date in 1970.

I guess there's no real way of knowing which time format is being used in the table, and either way some users are going to miss out? Question is do more people use milliseconds or seconds for the epoch?

Just thought it was worth mentioning

<img width="356" alt="image" src="https://user-images.githubusercontent.com/27215476/163233862-4874e45a-b2e6-43f6-a23e-e5e4f6abf4d6.png">

**Comment by liesislukas** [comment]
31K years in future will make you still 12 symbols in seconds
3K years in future will make you still 11 symbols in seconds

so i would argue it's quite safe to assume if timestamp is 11 symbols or longer, that's milliseconds.

also could check if it's 1970, probably wrong format picked.  

couple simple if cases and issue would be resolved :)
