### ISSUE TITLE
looking for more collaborators

### ISSUE THREAD

**Issue by aaronshaf** [aaronshaf/dynamodb-admin#3]
Put in a decent PR and I'd be happy to give you git push privileges, etc.

**Comment by gpsamson** [comment]
Opened a minor PR. Will definitely open more as I (or my team) makes changes.

**Comment by aaronshaf** [comment]
Thank you! A PR more substantive would be great for adding you as a collaborator.

**Comment by MatheusVellone** [comment]
I will open some issues and PRs as I have ideas for new features or find bugs

**Comment by aaronshaf** [comment]
A big thanks to @rchl... rchl, you have been incredible.

**Comment by benhutchins** [comment]
I’d like to be considered for becoming a contributor. I have another feature addition in development to continue where #90 left off. I may also add some better testing, as I think I discovered a bit of lacking there when working on #90

**Comment by aaronshaf** [comment]
@benhutchins I just invited you.
