### ISSUE TITLE
Upgrade AWS SDK from v2 to v3

### ISSUE THREAD

**Issue by DeeJEarl88** [aaronshaf/dynamodb-admin#379]
[Migrating to v3](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html)

**Comment by dgeller-OUHSC** [comment]
There is a [PR](https://github.com/aaronshaf/dynamodb-admin/pull/83) relating to this upgrade that's been languishing since 2019, Are there any plans to upgrade this to V3? We are getting warnings on the console that V2 is going into maintenance mode this year.

**Comment by rchl** [comment]
The PR got a bit outdated.
Feel free to contribute with a PR that updates to the latest version.
