### ISSUE TITLE
Make port configurable

### ISSUE THREAD

**Issue by nepatriots21** [aaronshaf/dynamodb-admin#38]
Could you please make the port dynamodb-admin runs on configurable from the terminal?  We have two dynamo instances running locally and 8001 is one of the ports we are using. I had to clone the project and modify the dynamodb-admin.js confnig.

**Comment by rchl** [comment]
I think it makes sense to add command line option for it but you _can_ configure port currently using environment variables `PORT`. On unix systems you would start using:
```
PORT=8005 dynamodb-admin
```
On Windows you probably need to do it in two steps:
```
set PORT=8005
dynamodb-admin
```

**Comment by nepatriots21** [comment]
Thanks!
