### ISSUE TITLE
Add possibility to inject express

### ISSUE THREAD

**Issue by gabrielgollo** [aaronshaf/dynamodb-admin#381]
Is there any possibility of improving the createServer function by adding this? With that, I could inject my own Express instance and use only one server with another GUI tool like this: https://github.com/ajyounguk/aws-sqs-sns-client.

![image](https://github.com/aaronshaf/dynamodb-admin/assets/65550482/1aca4e31-54e0-4bee-8cd9-82fc3fe3f2bb)

**Comment by rchl** [comment]
Feel free to create a PR.
