### ISSUE TITLE
Clear Install Instructions

### ISSUE THREAD

**Issue by srose4** [aaronshaf/dynamodb-admin#4]
Would you provide more details on setting the AWS_ACCESS_KEY_ID, etc please?  Meaning do I set these as environment variables, parameters in a file, json file, etc.  Thanks

**Comment by aaronshaf** [comment]
Sure. Great recommendation.

For now: Many of us specify the environment variables in the command line. Or you can use the [export](http://stackoverflow.com/a/7328289) command. I personally use [vaulted](https://github.com/miquella/vaulted/).

**Comment by michaelthwaite** [comment]
I think that we maybe need more :-)

For example, how do we connect to our local development dynamodb on localhost:8000? Actually, is that possible? Perhaps that's a recommendation. Thanks.

**Comment by macarthy** [comment]
+1  can you use this to  connect to our local development dynamodb on localhost:8000

**Comment by lordciccio** [comment]
This tool is especially thought for local development, since, on AWS, tables can be explored with aws management console.
Example of bash script lines to run dynamodb-admin:

export AWS_ACCESS_KEY_ID=local
export AWS_SECRET_ACCESS_KEY=local
export DYNAMO_ENDPOINT=http://localhost:8000
node index.js
