### ISSUE TITLE
Support reverse proxy path

### ISSUE THREAD

**Issue by ls-rein-martha** [aaronshaf/dynamodb-admin#418]
I am wondering if it is possible to have an env var that supports dynamodb-admin deployed behind reverse proxy

So for example 
- I would like to easily access dynamodb-admin at my multiple sbx cluster
- I have nginx that will have a path: `domain.com/sbx-env-1/dynamodb-admin/`
   - So I would like to have the `/sbx-env-1/dynamodb-admin` as a prefix in an env var
   - And dynamodb-admin will use that prefix for all the resources and URL
   - Without that, all the resources or href in the app will point to `domain.com/{assets}` instead of `domain.com/sbx-env-1/dynamodb-admin/{assets}`

**Comment by rchl** [comment]
I don't claim to understand this use case very much but I don't think this would be in scope of this problem. It would most likely be possible to set up a layer above to handle path rewrites and such.
