### ISSUE TITLE
Unable to work with tables having slash '/' in name

### ISSUE THREAD

**Issue by justdmitry** [aaronshaf/dynamodb-admin#424]
Tables with slash in name (like `myfolder/mytable`) are impossible to browse or edit: generated links look like `http://localhost:8001/tables/myfolder/mytable` and return 404.

This may be workarounded by manually updating link (by escaping `/` with `%2F`) to `http://localhost:8001/tables/myfolder%2Fmytable`, but editing links (also when working with items) is very annoying.

**Comment by rchl** [comment]
Slashes are not supported in table names - see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html

**Comment by justdmitry** [comment]
While slashes are not supported in "native" DynamoDB, they are supported in different "clones". For example, YandexDB is AWS-compatible and it supports slashes.

**Comment by rchl** [comment]
OK. It's technically the right thing to do to escape those params anyway.

**Comment by justdmitry** [comment]
I have sent you YandexDB access credentials in email so you can test escaping.

**Comment by rchl** [comment]
Thanks but I don't think I will need that. The fix should be pretty straightforward. You can test it afterwards :)

**Comment by rchl** [comment]
fixed in https://github.com/aaronshaf/dynamodb-admin/releases/tag/v5.1.1
