### ISSUE TITLE
Multi pages not being shown

### ISSUE THREAD

**Issue by gonzalo-roberto-diaz** [aaronshaf/dynamodb-admin#44]
In the `Scan` tab of any table, after looking by a filter, if the resultset spans more than one page,  additional pages are not shown. (Or, more precisely, no additional buttons saying `Page2`, `Page3` etc are shown, as it happened in previous versions).

I don't know it this is deliberate, just pointing it out.

**Comment by rchl** [comment]
Whether filtering or not, I can see a `Next page` button. So there doesn't seem to be any filtering-specific bug as far as I can see.

The problems I see:
  - no `Previous page` button
  - the label of the Scan tab always specifies all items count rather than filtered count
