### ISSUE TITLE
ArgumentParser superseding environment variables for options?

### ISSUE THREAD

**Issue by rbonestell** [aaronshaf/dynamodb-admin#449]
Hery @aaronshaf !

It seems that as a result of PR #447 that dynamodb-admin is no longer utilizing the environment variables to initialize the service.

My team uses your [docker image](https://hub.docker.com/r/aaronshaf/dynamodb-admin) for our local development stack, providing the following env vars:

```yaml
environment:
  - DYNAMO_ENDPOINT=http://localstack:4566
  - AWS_REGION=us-west-2
  - AWS_ACCESS_KEY_ID=localstack
  - AWS_SECRET_ACCESS_KEY=localstack
```

Now, when dynamodb-admin v5.0.0 loads in docker, it prints the following:
```
2024-11-18 11:14:33   database endpoint:        http://localhost:8000
2024-11-18 11:14:33   region:           us-west-2
2024-11-18 11:14:33   accessKey:                localstack
2024-11-18 11:14:33 
2024-11-18 11:14:33   dynamodb-admin listening on http://:::8001 (alternatively http://0.0.0.0:8001)
```

This is likely due to the release v5.0.0 introducing `ArgumentParser` in [bin/dynamodb-admin.ts](https://github.com/aaronshaf/dynamodb-admin/compare/v4.6.2...v5.0.0#diff-e1c48a8d485e36a1028494b2cd01f120fdb95d517d9a9459660702668bafb4e9) and the default values may be overriding env vars?

**Comment by rchl** [comment]
ArgumentParser was there before too but I'll look at this regression.
