### ISSUE TITLE
Docker image in the hub.docker.com

### ISSUE THREAD

**Issue by dplusic** [aaronshaf/dynamodb-admin#45]
Could you please maintain https://hub.docker.com/r/aaronshaf/dynamodb-admin ?
I want to use latest version of "dynamodb-admin" as a docker image.

**Comment by rchl** [comment]
@aaronshaf Ideally we would have automated builds created on new release of dynamodb-admin. Would you be able to set that up?

Documentation: https://docs.docker.com/docker-hub/builds/

**Comment by rchl** [comment]
@aaronshaf ping

**Comment by aaronshaf** [comment]
I'll look at this ASAP

**Comment by rchl** [comment]
Seems to work for me. Thank you.

(I'm thinking it might be better to build only releases (tagged commits) if possible, but not a big deal)
