### ISSUE TITLE
Broken npm package (views and public folders are missing)

### ISSUE THREAD

**Issue by justdmitry** [aaronshaf/dynamodb-admin#458]
Installing with `npm install -g dynamodb-admin` produces non-working result.

App starts, but index page fails with 500 status code and json response:

```json
{
  "view": {
    "defaultEngine": "ejs",
    "ext": ".ejs",
    "name": "tables",
    "root": "C:\\Users\\Dmitry\\AppData\\Roaming\\npm\\node_modules\\dynamodb-admin\\views"
  }
}
```

Specified `views` folder does not exist, my `dynamodb-admin` contains only `dist` and `node_modules` folders and `license`, `package.json` and `readme.md` files.

To fix this problem I need to manually copy `views` and `public` folders from source git repo.

Checked on v5.1.0 and v5.1.1 using Windows 11 with Node 20.13.1.

**Comment by rchl** [comment]
Ops. Fixed in https://github.com/aaronshaf/dynamodb-admin/releases/tag/v5.1.3
