### ISSUE TITLE
Displaying all item's content slows down loading considerably

### ISSUE THREAD

**Issue by gonzalo-roberto-diaz** [aaronshaf/dynamodb-admin#47]
This is a change in relation to previous versions, where only sections of some fields were showing.
I think it is a bad idea. Even for tables a few, but quite large items, the loading slows down to the point of showing a progress indicator for several seconds. I recommend finding a compromise for speed here.

**Comment by gonzalo-roberto-diaz** [comment]
I will attach the whole database. The culprit is the  `songs` file, heavy in json entries as you correctly suspect.[
[shared-local-instance.db.gz](https://github.com/aaronshaf/dynamodb-admin/files/2289013/shared-local-instance.db.gz)
](url)

**Comment by rchl** [comment]
This dump seems to be in sqlite format. Would I need to use something like https://github.com/msolnit/sqlite-to-dynamodb to import it? (I'm testing on local dynamodb so can't use AWS frontend).

**Comment by rchl** [comment]
I have manually imported the `songs` table and I can indeed see that browser gets quite bogged down when doing layout. I have made some changes locally (different rendering of items) that appear to help a lot with this problem.

**Comment by rchl** [comment]
You can try version 3.0.0.

I've noticed that it was not so much JSON.stringify call but browser layouting long lines in table that was slow. So now that I'm using library for formatting items, while likely slower than JSON.stringify, makes layouting and overall loading much faster in the end.
