### ISSUE TITLE
the `--port` flag doesn't change port

### ISSUE THREAD

**Issue by claytron5000** [aaronshaf/dynamodb-admin#48]
When running the interface from the command line, the `--port` flag doesn't appear to run the app on another port.

```
$dynamodb-admin --port 8002
dynamodb-admin
    listening on http:0.0.0.0:8001
```
I've tried `--port=8002` `-p 8002` `-p=8002`.

**Comment by rchl** [comment]
Output is slightly different from what I would expect. Are you sure this is the latest version? `dynamodb-admin --version` should say `2.0.6`.

**Comment by claytron5000** [comment]
That's what's weird, it's almost like it's not receiving any arguments:

```
❯ dynamodb-admin --version         
dynamodb-admin
  DYNAMO_ENDPOINT is not defined (using default of http://localhost:8000)
  listening on http://0.0.0.0:8001
```
So it just runs the application instead of receiving the `--version` argument (option?)

When I dig into my global node_modules I can see `"_id": "dynamodb-admin@2.0.4",` in the packages.json. I'll update and see if that fixes the issue.

**Comment by claytron5000** [comment]
Updating fixed the issue.
