### ISSUE TITLE
Can't start the gui

### ISSUE THREAD

**Issue by czar82** [aaronshaf/dynamodb-admin#50]
My DynamoDB is correctly running, I can open the shell on http://localhost:8000/shell/#

npm install dynamodb-admin -g
run fine.

export DYNAMO_ENDPOINT=http://localhost:8000
Give me error, "export" program is unrecognized. But it's still ok because DynamoDB is already by default on my localhost:8000

dynamodb-admin -o
dynamodb-admin
  DYNAMO_ENDPOINT is not defined (using default of http://localhost:8000)
  listening on http://0.0.0.0:8001
But the webpage that will be open on http://0.0.0.0:8001/ say it's impossible to reach the site. (I tried with other ports too, but it doesn't work).

Can you help me? Sorry for the noob question.

**Comment by czar82** [comment]
The url was obviously: 
http://localhost:8001/

**Comment by rchl** [comment]
Well, 0.0.0.0 is a broadcast address and that should normally work too. Given that `export` command didn't work for you, I take it that you are on windows. I'm not sure but it could be either Windows-specific issue or something in your setup (firewall maybe) that makes this not work.

**Comment by czar82** [comment]
Yes, I'm on windows. With http://localhost:8001/ it works.
Maybe would be nice have something like:
dynamodb-admin -o http://localhost:8001/
