### ISSUE TITLE
Dynalite crashes on opening the gui

### ISSUE THREAD

**Issue by cdm430** [aaronshaf/dynamodb-admin#51]
Not sure if this is an issue with dynalite or dynamodb-admin per se.

When I run a dynalite server, as soon as I run dynamodb-admin and open a browser, dynalite crashes with this error:

```node_modules\level-iterator-stream\index.js:16
  this.on('end', this.destroy.bind(this, null, null))
                              ^

TypeError: Cannot read property 'bind' of undefined
```

Has anyone else come across this? It seems to work fine when using local-dynamo (a thin wrapper around AWS DynamoDB Local).

Thanks

**Comment by cdm430** [comment]
If I run dynalite using a globally installed version (just running `dynalite` from the command line), it seems to work fine. If I run dynalite via a simple node script like this:
```
var dynalite = require('dynalite'),
    dynaliteServer = dynalite({path: './mydb', createTableMs: 50})
 
// Listen on port 4567
dynaliteServer.listen(4567, function(err) {
  if (err) throw err
  console.log('Dynalite started on port 4567')
})
```

Then as soon as I launch dynamodb-admin (via
` cross-env DYNAMO_ENDPOINT=http://localhost:4567 dynamodb-admin --open ` )
 then dynalite crashes with the available trace as:
```
node_modules\level-iterator-stream\index.js:16
  this.on('end', this.destroy.bind(this, null, null))
                              ^

TypeError: Cannot read property 'bind' of undefined
    at new ReadStream (node_modules\level-iterator-stream\index.js:16:31)
    at LevelUP.readStream.LevelUP.createReadStream (node_modules\levelup\lib\levelup.js:274:10)
    at LevelUP.keyStream.LevelUP.createKeyStream (node_modules\levelup\lib\levelup.js:279:15)
    at Object.listTables node_modules\dynalite\actions\listTables.js:11:25)
    at IncomingMessage.<anonymous> (node_modules\dynalite\index.js:260:20)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rchl** [comment]
Doesn't look like it's specific to dynamodb-admin. I would guess that it's either due to node version or the fact that you are on Windows. Looks like `ReadStream`'s (from the `level-iterator-stream` package) implementation of `destroy()`  doesn't get registered by superclass. I don't know why though.

I'm on Mac.
Node 8.11.3.
Dynalite 2.0.0
