### ISSUE TITLE
Does not work with docker image

### ISSUE THREAD

**Issue by sashokbg** [aaronshaf/dynamodb-admin#52]
I have a local docker container running dynamodb and the dynamodb-admin cannot list the tables.

It seems like dynamodb-admin is somehow connected to a different instance of the dynamodb since I can list my tables using aws cli:

aws dynamodb list-tables --endpoint-url http://127.0.0.1:8000 --region eu-west-2

{
    "TableNames": [
        "Job",
        "Music",
        "MusicCollection"
    ]
}

AWS_REGION=eu-west-2 DYNAMO_ENDPOINT=http://127.0.0.1:8000 dynamodb-admin

Shows nothing in the browser.

Any ideas ?

**Comment by aheissenberger** [comment]
I had a similar problem and solved it by using the same configuration as used by the app - e.g.:
```
AWS_SECRET_ACCESS_KEY=fake AWS_ACCESS_KEY_ID=fake AWS_REGION=us-fake-1 DYNAMO_ENDPOINT=http://localhost:8000 dynamodb-admin
```

**Comment by rchl** [comment]
DYNAMO_ENDPOINT you are trying to use is the same as default and region/key doesn't matter for local instance so I can't really see what's wrong. Maybe there is some error in the browser in inspector's console?

**Comment by sashokbg** [comment]
@aheissenberger you are absolutely right, it worked !

It seems that my tables and items were created using my real AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY so it probably created internally a new instance with the triple [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION]

You should probably update your README and code :)

**Comment by rchl** [comment]
I don't really understand what the problem was.

If you don't specify ID/SECRET then it will use some `key`/`secret`. Why did that not work for you? Do you need to use actual ID/SECRET that you have defined in your `~/.aws/credentials`? I thought that local instance of dynamodb accepts any ID/SECRET so it should work regardless?

**Comment by sashokbg** [comment]
It seems that a dynamodb instance is defined by **[REGION, KEY, SECRET]**. When you start the dynamodb-admin app it uses dummy **key/secret** so your instance is **['us_east-1', 'key', 'secret']**

Then I start my real application that reads my real **key/secret** inside **~/.aws/credentials** and tries to connect to ['eu-west-1', 'my-real-key', 'my-real-secret'] which is NOT the same base, thus the behavior described in my original post.

**Comment by sashokbg** [comment]
Here is the documentation that supports my claim:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html

`
If you use the -sharedDb option, DynamoDB creates a single database file named shared-local-instance.db. Every program that connects to DynamoDB accesses this file. If you delete the file, you lose any data that you have stored in it.

If you omit -sharedDb, the database file is named myaccesskeyid_region.db, with the AWS access key ID and Region as they appear in your application configuration. If you delete the file, you lose any data that you have stored in it.
`

**Comment by sashokbg** [comment]
#53

**Comment by rchl** [comment]
Fix integrated.

**Comment by mrthebob** [comment]
This doesn't seem to be fixed for me - it's not reading the ~/.aws/credential file -- I have to specify them manually, and I'm using v3.1.0

**Comment by rchl** [comment]
Are your credentials stored in `[default]` section in credentials file?

**Comment by rchl** [comment]
Also, correct file name is `~/.aws/credentials` ('s' is missing in the path you wrote).
