### ISSUE TITLE
GUI not displaying any table

### ISSUE THREAD

**Issue by maane018** [aaronshaf/dynamodb-admin#57]
I have DynamoDB running on localhost:8000.
<img width="560" alt="screen shot 2018-10-04 at 3 05 20 pm" src="https://user-images.githubusercontent.com/11513835/46465705-f153b300-c7e6-11e8-9b6c-1a3a4c49f138.png">
Now, when I run the AWS command ```aws dynamodb list-tables --endpoint-url http://localhost:8000```,  the output is:
<img width="549" alt="screen shot 2018-10-04 at 3 06 11 pm" src="https://user-images.githubusercontent.com/11513835/46465760-10524500-c7e7-11e8-95f2-6f667abe59e1.png">

But these 2 tables are not there on the GUI. 
I tried setting the same AWS Region i.e us-west-2, but still it is not coming.
<img width="735" alt="screen shot 2018-10-04 at 3 07 14 pm" src="https://user-images.githubusercontent.com/11513835/46465806-37107b80-c7e7-11e8-9d40-2b5c95aa5f85.png">

**Comment by rchl** [comment]
aws client might be using different access key (read from your ~/.aws/credentials). You could try to match it by setting AWS_ACCESS_KEY_ID to same value.
Region also has to match.

In-progress PR #53 might help to make this "just work".

**Comment by maane018** [comment]
Yes. I had to manually give my AWS secret key and ID.
It worked.
Thanks.
