### ISSUE TITLE
Get with # in key

### ISSUE THREAD

**Issue by yoavain-sundaysky** [aaronshaf/dynamodb-admin#70]
I have a key with the # character and I can't use the get function. 
Scan function works fine.

Error message shows that it trims everything from the first # until the end:
"Cannot GET /tables/TABLE_NAME/items/KEY_UNTIL_HASH"

**Comment by rchl** [comment]
Fixed in v3.1.1 with f909e48446eadd9401878dd4095cb260f3f4c1e3
