### ISSUE TITLE
No option to change dynamo-endpoint in command line.

### ISSUE THREAD

**Issue by dbteku** [aaronshaf/dynamodb-admin#74]
This is more of a feature request. You cannot run 2 different instances of dynamodb-admin pointing to 2 different dynamo endpoints. Such as http://localhost:8000 and http://localhost:8010. It would be nice to have a -d option to put in a different dynamo endpoint without having to use an env variable.

**Comment by rchl** [comment]
You can set environment variable per instance of dynamodb-admin like so:

DYNAMO_ENDPOINT=http://localhost:8000 dynamodb-admin --port 8001
DYNAMO_ENDPOINT=http://localhost:8010 dynamodb-admin --port 8002

Of course those would have to be started in two different instances of terminal.
And on Windows this syntax will not work but there are alternative options.

Of course it wouldn't hurt to also have command line option to change endpoint...

**Comment by dbteku** [comment]
Thanks for that. It's just a feature request to make it much easier to user when having multiple apps open that work together to debug across all of them.

**Comment by rchl** [comment]
`--dynamo-endpoint` CLI argument was added as part of https://github.com/aaronshaf/dynamodb-admin/pull/447/files
