### ISSUE TITLE
Update version in the Docker Image

### ISSUE THREAD

**Issue by wleite** [aaronshaf/dynamodb-admin#77]
I am currrent moving our stack to use docker in the development to make easy to create the dev env with all the tools that we need, but right now the Docker Image for Dynamo Admin are not using the latest version.

What is the current plan to update the docker images?

**Comment by rchl** [comment]
Being a contributor, I don't have access to docker account so I can only reach out to @aaronshaf. I've sent email already some days ago.

**Comment by aaronshaf** [comment]
Sorry for delay. Will try to fix in the morning.

**Comment by aaronshaf** [comment]
@rchl I have you listed as a collaborator on docker.com, which gives you "push and pull access to this repository"

**Comment by aaronshaf** [comment]
Looks like I need to reconfigure autobuilds. Looking...

**Comment by rchl** [comment]
@aaronshaf I can see myself listed as collaborator but that doesn't give me access to project setting, I believe.

**Comment by aaronshaf** [comment]
Success! Fresh build done. Autobuilds set up again.
